{
    "id": "CVE-2025-56558",
    "sourceIdentifier": "cve@mitre.org",
    "published": "2025-10-29T17:15:35.760",
    "lastModified": "2025-10-29T17:15:35.760",
    "vulnStatus": "Received",
    "cveTags": [],
    "descriptions": [
        {
            "lang": "en",
            "value": "An issue discovered in Dyson App v6.1.23041-23595 allows unauthenticated attackers to control other users' Dyson IoT devices remotely via MQTT."
        }
    ],
    "metrics": [],
    "references": [
        {
            "url": "http:\/\/dyson.com",
            "source": "cve@mitre.org"
        },
        {
            "url": "https:\/\/archive.org\/details\/dyson-acpolicy-bug-report",
            "source": "cve@mitre.org"
        }
    ]
}