{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2025-4435",
            "ASSIGNER": "cna@python.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/github.com\/python\/cpython\/commit\/19de092debb3d7e832e5672cc2f7b788d35951da",
                    "name": "https:\/\/github.com\/python\/cpython\/commit\/19de092debb3d7e832e5672cc2f7b788d35951da",
                    "refsource": "",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/python\/cpython\/commit\/3612d8f51741b11f36f8fb0494d79086bac9390a",
                    "name": "https:\/\/github.com\/python\/cpython\/commit\/3612d8f51741b11f36f8fb0494d79086bac9390a",
                    "refsource": "",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/python\/cpython\/commit\/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
                    "name": "https:\/\/github.com\/python\/cpython\/commit\/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
                    "refsource": "",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/python\/cpython\/commit\/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
                    "name": "https:\/\/github.com\/python\/cpython\/commit\/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
                    "refsource": "",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/python\/cpython\/issues\/135034",
                    "name": "https:\/\/github.com\/python\/cpython\/issues\/135034",
                    "refsource": "",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/python\/cpython\/pull\/135037",
                    "name": "https:\/\/github.com\/python\/cpython\/pull\/135037",
                    "refsource": "",
                    "tags": []
                },
                {
                    "url": "https:\/\/mail.python.org\/archives\/list\/security-announce@python.org\/thread\/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG\/",
                    "name": "https:\/\/mail.python.org\/archives\/list\/security-announce@python.org\/thread\/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG\/",
                    "refsource": "",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "When using a TarFile.errorlevel = 0\u00a0and extracting with a filter the documented behavior is that any filtered members would be skipped and not extracted. However the actual behavior of TarFile.errorlevel = 0\u00a0in affected versions is that the member would still be extracted and not skipped."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2025-06-03T13:15Z",
    "lastModifiedDate": "2025-06-03T15:15Z"
}