{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2025-3136",
            "ASSIGNER": "cna@vuldb.com"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": [
                        {
                            "lang": "en",
                            "value": "CWE-119"
                        }
                    ]
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/github.com\/pytorch\/pytorch\/issues\/149821",
                    "name": "https:\/\/github.com\/pytorch\/pytorch\/issues\/149821",
                    "refsource": "",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/pytorch\/pytorch\/issues\/149821#issue-2940838975",
                    "name": "https:\/\/github.com\/pytorch\/pytorch\/issues\/149821#issue-2940838975",
                    "refsource": "",
                    "tags": []
                },
                {
                    "url": "https:\/\/github.com\/pytorch\/pytorch\/issues\/149821#issuecomment-2765311086",
                    "name": "https:\/\/github.com\/pytorch\/pytorch\/issues\/149821#issuecomment-2765311086",
                    "refsource": "",
                    "tags": []
                },
                {
                    "url": "https:\/\/vuldb.com\/?ctiid.303041",
                    "name": "VDB-303041 | CTI Indicators (IOB, IOC, IOA)",
                    "refsource": "",
                    "tags": []
                },
                {
                    "url": "https:\/\/vuldb.com\/?id.303041",
                    "name": "VDB-303041 | PyTorch CUDACachingAllocator.cpp torch.cuda.memory.caching_allocator_delete memory corruption",
                    "refsource": "",
                    "tags": []
                },
                {
                    "url": "https:\/\/vuldb.com\/?submit.525252",
                    "name": "Submit #525252 | pytorch pytorch (in torch.cuda.memory.caching_allocator_delete) torch 2.6.0 invalid memory access",
                    "refsource": "",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "A vulnerability, which was classified as problematic, has been found in PyTorch 2.6.0. This issue affects the function torch.cuda.memory.caching_allocator_delete of the file c10\/cuda\/CUDACachingAllocator.cpp. The manipulation leads to memory corruption. An attack has to be approached locally. The exploit has been disclosed to the public and may be used."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": {
        "baseMetricV3": {
            "cvssV3": {
                "version": "3.1",
                "vectorString": "CVSS:3.1\/AV:L\/AC:L\/PR:L\/UI:N\/S:U\/C:N\/I:N\/A:L",
                "attackVector": "LOCAL",
                "attackComplexity": "LOW",
                "privilegesRequired": "LOW",
                "userInteraction": "NONE",
                "scope": "UNCHANGED",
                "confidentialityImpact": "NONE",
                "integrityImpact": "NONE",
                "availabilityImpact": "LOW",
                "baseScore": 3.3,
                "baseSeverity": "LOW"
            },
            "exploitabilityScore": 1.8,
            "impactScore": 1.4
        }
    },
    "publishedDate": "2025-04-03T04:15Z",
    "lastModifiedDate": "2025-04-03T04:15Z"
}